### ISSUE TITLE
Save to dropbox does not work

### ISSUE THREAD

**Issue by davidseoane** [Cores-ts/Fundingbox-support#100]
I have uploaded a document to one space. I have used the "save to dropbox" function. I log-in to Dropbox, select folder / route and seems to work, but when I save the document this does not appear on Dropbox

**Comment by xurxo** [comment]
This should be working again

**Comment by davidseoane** [comment]
Not closed. Does not work yet

**Comment by davidseoane** [comment]
OK, SOLVED WITH NEW FILES, NOT OLD ONES
