### ISSUE TITLE
PDF document does not dowload

### ISSUE THREAD

**Issue by davidseoane** [Cores-ts/Fundingbox-support#101]
When I try to dowload a pdf document from one space, this does not work. The following message appears:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>4CA67F055DB3936E</RequestId>
<HostId>
VNvUfoGXkcbNaODvT7uo0Iq/77XpK2CJbk23n0U6H4Lr0AQpw0snO6cmyaP5GhljNEBRXgCkgrQ=
</HostId>
</Error>

**Comment by xurxo** [comment]
This is working again, but only for new uploaded files, not the old ones.
We're trying to recover the old files, but for the moment old links won't resolve

**Comment by davidseoane** [comment]
OK, SOLVED WITH NEW FILES
