### ISSUE TITLE
Replies to documents do not work

### ISSUE THREAD

**Issue by davidseoane** [Cores-ts/Fundingbox-support#109]
@xurxo When I have a document in a chat and I try to reply to add a comment to such a document, the application re-starts and takes me to login again. I login and then the document appears twice and no comments added

**Comment by xurxo** [comment]
Could you please to try again? and close the issue if it's solved or add a new comment if not

**Comment by davidseoane** [comment]
Not solved yet :(

**Comment by davidseoane** [comment]
Tried with new files and do not work yet

**Comment by xurxo** [comment]
I can't reproduce this.
The page refreshes when you click the document or when you write the message?
It happens with all the files?

Please, try to attach an screenshot showing the link you're clicking.
Thanks

**Comment by davidseoane** [comment]
I go through the document to make a "reply"
![image](https://cloud.githubusercontent.com/assets/20294532/17325356/63ba15fe-58ab-11e6-9f45-593939309b29.png)
When I try ro reply (e.g. to make a comment) the login page appears
![image](https://cloud.githubusercontent.com/assets/20294532/17325378/8309aa78-58ab-11e6-891d-c89c40e7b7be.png)
I go through the document again and nothing has happened (same screenshot than 1t)

**Comment by xurxo** [comment]
I see, and this only happens on Direct chats, but not in the group spaces, right?

**Comment by davidseoane** [comment]
Yes, happens only in chats

**Comment by xurxo** [comment]
I think this is fixed now, please check it and close the issue if it's solved

**Comment by davidseoane** [comment]
Solved!!
