### ISSUE TITLE
Using a direct link

### ISSUE THREAD

**Issue by tmazuryk** [Cores-ts/Fundingbox-support#11]
When using a direct link e.g. http://fundingbox.com/profiles/incense
show a screen like this for good 10 seconds, before it renders properly. I have already managed to close the page...

![zrzut ekranu 2016-01-22 o 16 42 32](https://cloud.githubusercontent.com/assets/16816225/12515151/34f35c10-c127-11e5-871b-ee6327d53159.png)

**Comment by xurxo** [comment]
Humm, I see, the thing is we preload most part of the content to create a more fluid navigation, but maybe it's not the right idea if you're going directly to a profile page.

 Additionally we need a spinner there...

**Comment by tmazuryk** [comment]
Yep, sometimes you need to show during a presentation a direct link (I am just preparing a PPT). Or promote something in a newsletter. Than you give a direct link....
