### ISSUE TITLE
I can't log out my user in Fundingbox

### ISSUE THREAD

**Issue by xabichao** [Cores-ts/Fundingbox-support#114]
When I press the Logout option (see the picture below) it doesn't logout it only upload again the page to http://fundingbox.com/discover but I'm still remain logged with the same user. It happens using Chrome v. 52
![captura de pantalla 2016-08-14 a las 20 23 34](https://cloud.githubusercontent.com/assets/16784066/17651005/107cb106-625d-11e6-8290-0b525b75df64.png)

**Comment by xurxo** [comment]
Thanks for reporting this, we'll confirm it

**Comment by xurxo** [comment]
Closing old issues that should be fixed now
