### ISSUE TITLE
Duplication of text in the Space Description

### ISSUE THREAD

**Issue by xabichao** [Cores-ts/Fundingbox-support#115]
I have created I new private Space using Chrome. Once I press the buttom to end the process of Space creation what I see in the screen is what you can see in the screenshot below. The description of the Space appears duplicated. 

![captura de pantalla 2016-08-14 a las 20 29 46](https://cloud.githubusercontent.com/assets/16784066/17651044/f1b68c6e-625d-11e6-938a-c1ab73f31260.png)

**Comment by xurxo** [comment]
Duplicated #124
