### ISSUE TITLE
The figures of the Spaces announced in the microsite 20kDD don't match with the actual figures of such Spaces 

### ISSUE THREAD

**Issue by xabichao** [Cores-ts/Fundingbox-support#117]
See the picture below. You can see that DD CPS Space include 28 messages and 10 members, notwithstanding, if you Join such Space you can check that this Space it has only 18 messages and 2 members...

![captura de pantalla 2016-08-15 a las 17 56 03](https://cloud.githubusercontent.com/assets/16784066/17670313/aefdc8ce-6311-11e6-86b9-d5ba0c51bd18.png)

**Comment by xurxo** [comment]
Fixed
