### ISSUE TITLE
When I delete a message in a Space it is deleted but a "track" appears

### ISSUE THREAD

**Issue by davidseoane** [Cores-ts/Fundingbox-support#122]
I delete a message from a Space and is deleted but the "deleted message" appears. I´m the only one who see this or other users can? (I send screenshot)

![image](https://cloud.githubusercontent.com/assets/20294532/17890540/f65752e6-6936-11e6-852a-c6b5d2358689.png)

**Comment by xurxo** [comment]
This is how it should be, because some people could read it, and then search for it. 
We should notice it was deleted.

If you want to remove it completely, you should do it in gear as admin
