### ISSUE TITLE
Uploaded file appears several times (currently 11 times the same document)

### ISSUE THREAD

**Issue by davidseoane** [Cores-ts/Fundingbox-support#123]
I have uploaded a document once but appears 3 times in the space. How can I delete? I´m not currently able. I send screenshot: it is a file in the DD Robotics space
![image](https://cloud.githubusercontent.com/assets/20294532/17890573/3aa8db54-6937-11e6-9a67-98b486f7ed4b.png)

**Comment by davidseoane** [comment]
Keeps unsolved an now the file appears a lot of more times! (11) 
![image](https://cloud.githubusercontent.com/assets/20294532/18135756/3fd06f94-6fa3-11e6-9d3c-49029f112420.png)

**Comment by xurxo** [comment]
It looks like there is only 1 doc, but showing it many times, probably a UI bug. We'll check it.

**Comment by xurxo** [comment]
Closing old issues that should be fixed now
