### ISSUE TITLE
Can't updoad image in a profile through dashboard

### ISSUE THREAD

**Issue by AEscrich** [Cores-ts/Fundingbox-support#125]
I have tried to upload an image from my laptop into a profile through dashboard and I get the message "There was an error uploading your file" (you can see it in the attached screenshot).
I am using Chrome (Version 53.0.2785.89 m), file extension was "jpg" and size 98KB.  
Are there any format or size restrictions?

![image](https://cloud.githubusercontent.com/assets/17195391/18304844/03744114-74e5-11e6-8456-38083cd76b34.png)

**Comment by xurxo** [comment]
Probably we changed the credentials to upload to this bucket. Need to confirm it.

**Comment by xurxo** [comment]
Almu, a hotfix for this was deployed, please confirm if its fixed and close the issue if everything is ok.
Thanks

**Comment by AEscrich** [comment]
Hi, just to confirm this is already fixed. 

I have uploaded an image to [Neptune profile](http://fundingbox.com/profiles/new-cross-sectoral-value-chains-for-smes-innovation-in-blue-growth) today and it worked properly.

Thanks!
