### ISSUE TITLE
No download

### ISSUE THREAD

**Issue by iwonac** [Cores-ts/Fundingbox-support#138]
- i am in the evaluation section
- i go to the project by indygo!
- go to the 5.9 section i click on "Download file" (I expect some additional information provided by the user)
- new tab opens and this new tab displays application. No download starts.

**Comment by xurxo** [comment]
Thanks for reporting this.
It seems the download link is present even if the user didn't upload a file.

I'm marking this issue to be fixed ASAP

**Comment by xurxo** [comment]
I'm closing this as it seems solved now.
