### ISSUE TITLE
merged applications

### ISSUE THREAD

**Issue by iwonac** [Cores-ts/Fundingbox-support#139]
- i evaluate the application
- i go back to the list of applications
- i choose another application
- two applications are merged (e.g. 2.1 names) some fields remain from the previous application (5.3 applicant's history)
![merge-bug-07 02](https://cloud.githubusercontent.com/assets/25619093/22708070/34c0bb72-ed75-11e6-806b-077104e2bba3.png)

**Comment by xurxo** [comment]
Could you add some info about the browser and OS?

**Comment by iwonac** [comment]
Chrome  56.0.2924.87
Win 7 (64 bit)

**Comment by xurxo** [comment]
Thanks I'll try to reproduce it and I'll back to you

**Comment by xurxo** [comment]
Finally I was able to reproduce this issue and we're building a patch.
We'll deploy it in the next release. I'll tell you.

Thanks

**Comment by xurxo** [comment]
This was fixed in the last release.
Please, recheck it and reopen the issue if the problem persists.
