### ISSUE TITLE
Can't remove a TAG

### ISSUE THREAD

**Issue by tmazuryk** [Cores-ts/Fundingbox-support#140]
https://gear.fundingbox.com/opencalls/2c9ce88120a501a10c45ed66/apps/a744582bd6b0b769839ba3ff

![pastedgraphic-13](https://cloud.githubusercontent.com/assets/16816225/22829908/f33a17ac-efa4-11e6-894d-d3a0fbfc6810.png)

**Comment by xurxo** [comment]
Right now it's not possible to remove **all** the tags

**Comment by xurxo** [comment]
This should be already fixed, please recheck it
