### ISSUE TITLE
Can't see subsequent batch of applications

### ISSUE THREAD

**Issue by iwonac** [Cores-ts/Fundingbox-support#145]
![only10](https://cloud.githubusercontent.com/assets/25619093/22866346/630c68ce-f175-11e6-983b-beaee5c308ed.png)

I choose to see my pending applications and I choose Display 10. How can I see next 10? There is no way to see the rest.

**Comment by xurxo** [comment]
This was fixed in the last deployed release, so I0m closing the issue.
IF the problem persists, please re-open it.

Regards,
Jorge
