### ISSUE TITLE
Please add TAGs to search among applications

### ISSUE THREAD

**Issue by tmazuryk** [Cores-ts/Fundingbox-support#146]
![pastedgraphic-17](https://cloud.githubusercontent.com/assets/16816225/22890642/464fcfbc-f20d-11e6-82c0-1531f5cdc8ab.png)
![pastedgraphic-18](https://cloud.githubusercontent.com/assets/16816225/22890650/4cf2c752-f20d-11e6-9623-763415b3c19f.png)

**Comment by xurxo** [comment]
We have added the option to edit tags from the evaluation view

**Comment by xurxo** [comment]
Deployed in last release
