### ISSUE TITLE
Download file - error message

### ISSUE THREAD

**Issue by iwonac** [Cores-ts/Fundingbox-support#148]
Evaluation konsultexpertdaniel (297fa189d547d2de0de59c69)
Once I want to download a file a get a message:

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
konsultexpertdaniel/Psychologia Online - K.E NEUCA.pdf
</Key>
<RequestId>3ECFFA1E36A7AE66</RequestId>
<HostId>
Uk7IzFnHR/TeBrY3vra55ViuSrVK/LgbIxVE3qJZNkKrjeYNRB63mgTal6Ajnwr8wwA/e4xV1cc=
</HostId>
</Error>

**Comment by xurxo** [comment]
Seems a problem with the "plus" sign in the filename.
I'll send you the link via email
