### ISSUE TITLE
Pending evaluations not visible

### ISSUE THREAD

**Issue by iwonac** [Cores-ts/Fundingbox-support#150]
I choose evaluations with the status pending, assigned to me and I got 0 results, despite the fact, that more than 30 is still awaiting my evaluation (I can see them, when I choose "All")
![zero-pending](https://cloud.githubusercontent.com/assets/25619093/22999758/6b67231e-f3dd-11e6-909a-cd715dd6cf0b.png)

**Comment by xurxo** [comment]
Thanks for reporting this.
We'll take a look and I'll tell you something.
Meanwhile, your pending evaluations are presents in the last 3 pages.
If you filter by evaluator, there are from page 12 to 15

**Comment by xurxo** [comment]
This should be fixed now, so I'm closing the issue.

**Comment by iwonac** [comment]
Dear Jorge,
I am not able to validate it as all evaluations have "submitted" status.
