### ISSUE TITLE
data from exportet files are incomplete

### ISSUE THREAD

**Issue by KasiaGoj** [Cores-ts/Fundingbox-support#155]
the excel with evaluations is incomplete. the scores from evaluators are missing and it's impossible to distinguish the different stages of evaluations (stage 3 and stage 4 are in the same columns)
[evaluations.Thu Mar 02 2017 07-52-14 GMT+0100 (Środkowoeuropejski czas stand.).xlsx](https://github.com/Cores-ts/Fundingbox-support/files/812966/evaluations.Thu.Mar.02.2017.07-52-14.GMT.0100.Srodkowoeuropejski.czas.stand.xlsx)

**Comment by xurxo** [comment]
I'm closing this as it seems to be solved.
