### ISSUE TITLE
Invitation to sharing an application doesn't work

### ISSUE THREAD

**Issue by KasiaGoj** [Cores-ts/Fundingbox-support#163]
a message from one of IMP Growth applicants "I tried to invite my collegues to my Impact Application  to edit it but they didn't receive my invitation submitted through your platform."

**Comment by xurxo** [comment]
This is a known bug, already fixed, waiting to be deployed, something that will happen within the next days

**Comment by KasiaGoj** [comment]
when do you expect it to be deployed? we still get questions about it.

**Comment by KasiaGoj** [comment]
today we got 4 questions about adding collaborators. is that going to be fixed before the deadline of IMPACT Growth (May 09)?

**Comment by xurxo** [comment]
This was already fixed. All the invited people should have access to their applications, even if they didn't receive the invitation email.
