### ISSUE TITLE
"save&continue" in application form only works when all fields are completed

### ISSUE THREAD

**Issue by KasiaGoj** [Cores-ts/Fundingbox-support#169]
"save&continue" in each section of application form only works when all fields are completed which is found annoying by applicants who prefer to complete the app form offline in MS Office files.
there should be a possibility to save anything that's already filled in.

**Comment by xurxo** [comment]
That's not gonna happen in the short term, we divided the form into sections to make it easier to fill the forms, so the sections should also be short.

I'll add this as a feature request and we'll discuss internally, but it's no planned to have this in the short term.

Thanks

**Comment by tmazuryk** [comment]
We must review the plan. This is very annoying and startups are complaining a lot. This is building negative image of our platform.

**Comment by xurxo** [comment]
We did it in the KO meeting in April, and taking in consideration the time we need to rebuild the architecture and the priorities we decided to postpone it till find the right time. 

We'll review it again in the next KO meeting in June. Thanks
