### ISSUE TITLE
late spaces notifications 

### ISSUE THREAD

**Issue by KasiaGoj** [Cores-ts/Fundingbox-support#172]
notifications from spaces are sent sometimes even after 24h. For example in case of IMP Growth "early" deadline it mattered that the notifications came after 8 PM (on May 9th), and it was really urgent situation requiring immediate response.

**Comment by xurxo** [comment]
We send spaces notifications once a day, a daily digest around 8PM.
Just to not SPAM the users.

If you need to send notifications to applicants you should use gear
