### ISSUE TITLE
uploaded files don't work

### ISSUE THREAD

**Issue by KasiaGoj** [Cores-ts/Fundingbox-support#174]
Again...
This subject was closed but still doesn't work.

GfA (last uploaded 11052017)
![image](https://cloud.githubusercontent.com/assets/17121557/25984079/d8c7e30a-36e8-11e7-9739-5f808f8aaf0d.png)
FAQ (last uploaded 10052017)
![image](https://cloud.githubusercontent.com/assets/17121557/25984130/2420dee2-36e9-11e7-8cb8-5e693aecae21.png)

**Comment by KasiaGoj** [comment]
I reuploaded those files in the morning and it doesn't work again...
![image](https://cloud.githubusercontent.com/assets/17121557/25999558/ec057454-3725-11e7-83a8-ea2fa9f0309b.png)

**Comment by xurxo** [comment]
I think right now is fixed (finally)
