### ISSUE TITLE
adding contributors to application form

### ISSUE THREAD

**Issue by KasiaGoj** [Cores-ts/Fundingbox-support#176]
invited contributors don't know they're invited because they don't receive any invitation

**Comment by adymowska** [comment]
We tested it with @fundingbox.com and people who are registered on the platform and it's works (they receive invitation via e-mail), but with e-mails that are not registered on the platform yet, and are outside @fundingbox any invitation sent to them, arrives to them.

**Comment by xurxo** [comment]
Arrives to who? Reviewing the logs we can see many invitations sent to the invited email

**Comment by adymowska** [comment]
F.e. annkozera@wp.pl, no e-mail recieved.

**Comment by xurxo** [comment]
The platform sent 3 invitations to this user on May 13, so I think it's OK.
We use many techniques to avoid reacing the SPAM folder, but you are sending a  lot of emails with very similar contents and subjects, and this could cause many providers to catalog your email as SPAM
