### ISSUE TITLE
Gear changes between OpenCalls while making evals

### ISSUE THREAD

**Issue by tmazuryk** [Cores-ts/Fundingbox-support#198]
1. In Gear I was doing evaluations  in IMPACT Poland
2. After finishing first one, I clicked on "Evaluations"
![zrzut ekranu 2017-07-25 o 23 12 27](https://user-images.githubusercontent.com/16816225/28594029-c97a7ce2-718e-11e7-9e74-6350a97216c1.png)
3. I came back to proper list of evals
4. After finishing second one, I clicked again on "Evaluations" and was directed to the list of Evaluations from Batch 01 (backup)

**Comment by tmazuryk** [comment]
In fact I need to close Gear and reopen it completely in order to continue evaluations in IMPACT Poland

**Comment by josealonsogarcia** [comment]
Closed as deployed on v1.9
