### ISSUE TITLE
Anyone can EDIT a profile?

### ISSUE THREAD

**Issue by DavidBernalFBOX** [Cores-ts/Fundingbox-support#20]
I have searched IMPACT accelerator profile and when I'm on in I can EDIT the profile. Why?
I see that all the profiles can be edited by anyone. some examples:
http://fundingbox.com/profiles/sme-instrument-2016-2017-phase-1
http://fundingbox.com/profiles/fast-track-funding-to-innovation

**Comment by xurxo** [comment]
All internal users where proposed as curators with the privilege to edit any existing profile.
This will be removed  in some weeks, but for now we need you to improve the existing content, that's why
