### ISSUE TITLE
Search of applications in Gear works weird

### ISSUE THREAD

**Issue by tmazuryk** [Cores-ts/Fundingbox-support#200]
Very often you don't find elements in gear BUT they are there
![pastedgraphic-2](https://user-images.githubusercontent.com/16816225/28891477-eccb09d6-77ca-11e7-9fab-8928d2cf6785.png)

![pastedgraphic-1](https://user-images.githubusercontent.com/16816225/28891481-efeae1a4-77ca-11e7-8b23-acb4a60cb83d.png)

**Comment by josealonsogarcia** [comment]
Closed as deployed on v1.9
