### ISSUE TITLE
How can I add an object to a collection curated by someone else....????

### ISSUE THREAD

**Issue by tmazuryk** [Cores-ts/Fundingbox-support#29]
I could have added objects to a collections curated by Xabi (BigDataTechnologies) and now I can also curate it and keep adding objects.

But I cannot Save objects to any other collections anymore....

**Comment by xurxo** [comment]
This is because Xabi added you as a curator just for this collection.
You can see your profile here: http://fundingbox.com/collections/big-data-technologies

**Comment by xurxo** [comment]
I mean, to add an item to a collection you should be the owner or a contributor.
(Owners can invite contributors)
