### ISSUE TITLE
I have Submit new content to Fundingbox 

### ISSUE THREAD

**Issue by DavidBernalFBOX** [Cores-ts/Fundingbox-support#31]
This information appears in the "curated" section. How can I delete it? http://fundingbox.com/profiles/david-bernal

**Comment by xurxo** [comment]
The user can't delete content, even if he posted it.
You should contact the support team for this... Now you can ask Almudena to do this

**Comment by DavidBernalFBOX** [comment]
Hola Jorge,



Tengo que trasladar la incidencia a Almudena?



Un saludo/Best regards



David Bernal López



*De:* Jorge Fernández [mailto:notifications@github.com]
*Enviado el:* viernes, 29 de enero de 2016 13:36
*Para:* Cores-ts/Fundingbox-support
*CC:* DavidBernalFBOX
*Asunto:* Re: [Fundingbox-support] I have Submit new content to Fundingbox
(#31)



Closed #31 <https://github.com/Cores-ts/Fundingbox-support/issues/31>.

—
Reply to this email directly or view it on GitHub
<https://github.com/Cores-ts/Fundingbox-support/issues/31#event-531239483>.

**Comment by xurxo** [comment]
Yo lo elimino, no te preocupes.

2016-01-29 13:38 GMT+01:00 DavidBernalFBOX <notifications@github.com>:
