### ISSUE TITLE
I can't switch from one account to another

### ISSUE THREAD

**Issue by DavidBernalFBOX** [Cores-ts/Fundingbox-support#32]
If I'm logged in with my david.bernal@econet-consultants.com account and I logout, when clicking again on "log in", automatically FBOX logs in with david.bernal@econet-consultants.com. The plattform does not allow me to choose another account when I logout.

**Comment by xurxo** [comment]
Aha, this is a known bug caused because we use a centralized a login service for more than 1 service.
Thanks for posting it
