### ISSUE TITLE
Unexplained error in sign up procedure

### ISSUE THREAD

**Issue by paololombardi** [Cores-ts/Fundingbox-support#33]
I tried to sign up, but it would give "Invalid value" (actually "Value not valid") without giving directions on how to make it valid. I had to make several trials and errors before understanding that name+surname was not a valid username (why?) and fundingbox.com email was not a valid email (why?).

![screenshot 2016-01-31 23 01 13](https://cloud.githubusercontent.com/assets/16993463/12705381/b91f19a6-c871-11e5-8af6-e91f2bea45ce.png)

**Comment by xurxo** [comment]
I think you were trying to signup with an email and username which was already registered... So the message should clarify this...
