### ISSUE TITLE
Error in new opencall 

### ISSUE THREAD

**Issue by adymowska** [Cores-ts/Fundingbox-support#35]
While creating a new opencall, there is automatically filled:
Tagline
Description
as:
The snapback adidas yeezy boost 350 for sale hats as said above http://www.gableswatch.com/new/adidas-yeezy-boost-kanye-west-for-sale.html have adidas yeezy

Is it OK? I do not understand this idea.

**Comment by xurxo** [comment]
This is weird...Could you share the URL you submitted to create the opencall?

**Comment by adymowska** [comment]
Hi Jorge,

Now, after log in I can’t open my profile.

Clic on @anna.dymowska do not open the list….??



Best,

Anna Dymowska



*From:* Jorge Fernández [mailto:notifications@github.com]
*Sent:* Wednesday, February 03, 2016 1:02 PM
*To:* Cores-ts/Fundingbox-support <Fundingbox-support@noreply.github.com>
*Cc:* adymowska <anna.dymowska@fundingbox.com>
*Subject:* Re: [Fundingbox-support] Error in new opencall (#35)



This is weird...Could you share the URL you submitted to create the
opencall?

—
Reply to this email directly or view it on GitHub
<https://github.com/Cores-ts/Fundingbox-support/issues/35#issuecomment-179187564>
.[image: Obraz usunięty przez nadawcę.]

**Comment by adymowska** [comment]
OK. It does not work on home page, after „explore” it works. Weird.



http://fundingbox.com/profiles/64855b6796ef3727f26a7c52/success





Pozdrawiam,

Anna Dymowska



*From:* Anna Dymowska | econet [mailto:anna.dymowska@econet-consultants.com]

*Sent:* Wednesday, February 03, 2016 2:10 PM
*To:* 'Cores-ts/Fundingbox-support' <
reply@reply.github.com
>
*Subject:* RE: [Fundingbox-support] Error in new opencall (#35)



Hi Jorge,

Now, after log in I can’t open my profile.

Clic on @anna.dymowska do not open the list….??



Best,

Anna Dymowska



*From:* Jorge Fernández [mailto:notifications@github.com
<notifications@github.com>]
*Sent:* Wednesday, February 03, 2016 1:02 PM
*To:* Cores-ts/Fundingbox-support <Fundingbox-support@noreply.github.com>
*Cc:* adymowska <anna.dymowska@fundingbox.com>
*Subject:* Re: [Fundingbox-support] Error in new opencall (#35)



This is weird...Could you share the URL you submitted to create the
opencall?

—
Reply to this email directly or view it on GitHub
<https://github.com/Cores-ts/Fundingbox-support/issues/35#issuecomment-179187564>
.[image: Obraz usunięty przez nadawcę.]

**Comment by xurxo** [comment]
We are cleaning some old issues, so I'm closing this.
Please reopen it if the problem persist
