### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by adymowska** [Cores-ts/Fundingbox-support#39]
Searching by "opencall", do not shows the list of all open calls. Wierd.
Answer: No Results
Your search returned no results

The same with "product"
Answer: list of profiles and users

and "organization"
Answer: list of  users

**Comment by xurxo** [comment]
The search is based in the name, tagline and tags.
Opencall is not the name of an Opencall (its a category), so there are no results... You should search for a term or opencall name like "sme instrument"

**Comment by adymowska** [comment]
Hi . OK. But this is not intuitive.

You see categories at home page like opencall, product, organization, so if
you want to se all open calls, you search for “opencall” this is intuitive
action.



You do not know all opencall’s names…



For me it would be important.



Best,

Anna Dymowska



*From:* Jorge Fernández [mailto:notifications@github.com]
*Sent:* Thursday, February 04, 2016 9:11 AM
*To:* Cores-ts/Fundingbox-support <Fundingbox-support@noreply.github.com>
*Cc:* adymowska <anna.dymowska@fundingbox.com>
*Subject:* Re: [Fundingbox-support] Search (#39)



The search is based in the name, tagline and tags.
Opencall is not the name of an Opencall (its a category), so there are no
results... You should search for a term or opencall name like "sme
instrument"

—
Reply to this email directly or view it on GitHub
<https://github.com/Cores-ts/Fundingbox-support/issues/39#issuecomment-179703238>
.[image: Obraz usunięty przez nadawcę.]

**Comment by xurxo** [comment]
Yeah, I undertand, this is why we'll release an update with specific sections to explore opencalls, products, etc... I think this will solve the issue
