### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by adymowska** [Cores-ts/Fundingbox-support#63]
How to save and leave settings area?
I must click twice or even 3 times to mark something, f.e. that I would like receive e-mails.
How to add a foto, without Gravatar?? I do not want to have Gravatar. Can I linked it with LinkedIn or Google +??

**Comment by xurxo** [comment]
Data saving is automatically.
To go back to fundingbox click the fundingbox logo.
Gravatar is the only service available for avatars right now.
