### ISSUE TITLE
Links in the text

### ISSUE THREAD

**Issue by Roi23** [Cores-ts/Fundingbox-support#65]
It's not possible to include hyperlinks inside the description of an item. 
This feature is very useful and must be possible in the platform.

**Comment by xurxo** [comment]
You can use markdown syntax to format the description of a profile, so you can also add links using this syntax:

[This link](http://example.net/) has no title attribute.

**Comment by xurxo** [comment]
`[This link](http://example.net/) has no title attribute.`
