### ISSUE TITLE
SOME SUGGESTIONS: Exploring organisations (tagging and listing)

### ISSUE THREAD

**Issue by davidseoane** [Cores-ts/Fundingbox-support#76]
When exploring organisations (http://fundingbox.com/explore/organizations) only "Startups" and "Accelerators" seem to be tagged / listed. However, I can see in the search engine that Universities, Research Centres, etc...are uploaded to FBOX. Will these be tagged as such? Which "tag"?
Organisations are sorted by "type", "market" and "popularity". Will not "by territory" be created? I think this is useful for many organisations looking for others
When sorting organisations maybe a reference to the number between parenthesis would be fine to get impact into a new comer (e.g. I  can see "Startups (5000)" and I say "wow, I want to be there...")

**Comment by xurxo** [comment]
We still don't have tagged all organizations, this is why we are not showing the categories yet.
The same applies for the locations

**Comment by xurxo** [comment]
Closing old issues
