### ISSUE TITLE
Cannot post new posts in Spaces

### ISSUE THREAD

**Issue by tmazuryk** [Cores-ts/Fundingbox-support#81]
After pressing enter nothing appears

**Comment by xurxo** [comment]
This is fixed now.
We are experimenting some connectivity issues with the DB that seems to affect some of the tools.
We are investigating this.

**Comment by tmazuryk** [comment]
My spaces are empty now:



Tomek

**Comment by xurxo** [comment]
Did you tried to reload the app? Try open it in an incognito tab, just to check...

**Comment by tmazuryk** [comment]
Yes, I have reloaded the app.

I cannot open in incognito tab, because it requires password that I don’t remember. I tried to reset it but http://accounts.fundingbox.com/settings <http://accounts.fundingbox.com/settings> shows blank page :-(

Tomek

**Comment by xurxo** [comment]
It shows a blank page? This is weird.
PLease, go to this URL to logout: http://accounts.fundingbox.com/?doLogout=true
Then click Forgot your password? And fill the form, you'll receive a new password in a minute

**Comment by tmazuryk** [comment]
OK, after few attempts I managed to reset password.

Now moved to Chrome and trying to open Spaces and I see blank screen and this URL (http://spaces.fundingbox.com/authorized#access_token=577f717eaf59fc8f6fb52428&token_type=Bearer&expires=1468056318&expires_in=86400 <http://spaces.fundingbox.com/authorized#access_token=577f717eaf59fc8f6fb52428&token_type=Bearer&expires=1468056318&expires_in=86400>) :-(

In Safari (my usual browser) I see empty Spaces.

Tomek

**Comment by xurxo** [comment]
OK, I need a few hours to investigate this

**Comment by xurxo** [comment]
We have increased the db connection pool and should be more stable now, please, try again

**Comment by tmazuryk** [comment]
Seems it is working now….

Tomek

**Comment by xurxo** [comment]
Good news, I'm closing the issue, reopen it if this happen again
