### ISSUE TITLE
Cannot sign in to dashboard

### ISSUE THREAD

**Issue by AEscrich** [Cores-ts/Fundingbox-support#85]
I cannot sign in at http://dashboard.fundingbox.com/ using Chrome. Error message in the screenshot:
![image](https://cloud.githubusercontent.com/assets/17195391/16729225/551c2876-476b-11e6-9f78-87eb0a93c8d1.png).

I haven't either been able to sign in using Firefox: it produces a blank page. Screenshot:
![image](https://cloud.githubusercontent.com/assets/17195391/16729362/2befd244-476c-11e6-8562-54f20e931927.png).

**Comment by AEscrich** [comment]
I am still experiecing this issue. I have tried both navigators (chrome and firefox), tried reloading the page, tried waiting and loading again, tried deleting navigation data and even rebooting and retrying, with no results.

Is there any way (maybe another navigator?) that I can sign in to dashboard to publish edit and publish the new profilesI have been adding lately?

**Comment by xurxo** [comment]
Hi Almu, could you try again now, it seems it's working for me.
