### ISSUE TITLE
Spaces doesn't allow to download document 

### ISSUE THREAD

**Issue by pilaranadon** [Cores-ts/Fundingbox-support#90]
When I try to download a document uploaded for someone else in a spaces, the following sreen appears

![image](https://cloud.githubusercontent.com/assets/20436397/16831545/d7d5eab8-49a5-11e6-86de-1183e4557e76.png)

**Comment by xurxo** [comment]
This is working again, but only for new uploaded files, not the old ones.
We're trying to recover the old files, but for the moment old links won't resolve
