### ISSUE TITLE
Cannot sign in to FundingBox using Chrome

### ISSUE THREAD

**Issue by AEscrich** [Cores-ts/Fundingbox-support#91]
I cannot sign in to FundingBox using Chrome (yesterday I was not able either). Screenshot of the error message:
![image](https://cloud.githubusercontent.com/assets/17195391/16833031/a3b7472e-49ad-11e6-8bc0-3a4b20573d25.png)

Also, when trying to sing in using Firefox, I get an error message (see screenshot bellow), although I am finally allowed to sign in if I click "continue" in the error message.

![image](https://cloud.githubusercontent.com/assets/17195391/16833081/edd33444-49ad-11e6-8510-9ef7ce9302e2.png)

**Comment by xurxo** [comment]
1 - We are experiencing some timeouts from the db, we are working t fix it, meanwhile just insist, the second time usually works ok.

2 - Probably your feed is tooo long, we can try limiting the results, we'll tell you

**Comment by xurxo** [comment]
We are cleaning some old issues, so I'm closing this.
Please reopen it if the problem persist
