### ISSUE TITLE
Unable to scroll down in the dashboard lists

### ISSUE THREAD

**Issue by AEscrich** [Cores-ts/Fundingbox-support#92]
I cannot see the complete lists at dashboard (profiles, collections, etc.) because I am not allowed to scroll down at a given point. In screenshot, the last rows I am able to see in the profiles list (example).

![image](https://cloud.githubusercontent.com/assets/17195391/16838588/2e8684b6-49ca-11e6-85e3-c7d307f4da53.png)

I am using Firefox (v 47.0).

**Comment by xurxo** [comment]
We are cleaning some old issues, so I'm closing this.
Please reopen it if the problem persist
